### ISSUE TITLE
회원가입 메일 인증

### ISSUE THREAD

**Issue by kyupid** [kyupid/java-chess-again#38]
튜토리얼: https://moonong.tistory.com/45

- [x] 본문 내용에  인증값을 인증url 쿼리스트링에 추가
- [x] 메일 보내기 (https://dlgkstjq623.tistory.com/287)
- [x]  서버에 생성된 인증값과 비교
 
---

done
https://github.com/kyupid/spring-security-signup-and-login/pull/4

---

gmail 보안 수준 낮은 앱의 액세스
https://myaccount.google.com/lesssecureapps

**Comment by kyupid** [comment]
1. 메일 보내기
2. 메일에 인증값 쿼리스트링에 추가
3. 클릭
4. 서버에 생성된 인증값과 비교

**Comment by kyupid** [comment]
```
java.lang.ClassNotFoundException: com.sun.mail.util.MailLogger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_312]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_312]
	at javax.mail.internet.MailDateFormat.<clinit>(MailDateFormat.java:154) ~[javax.mail-api-1.6.2.jar:1.6.2]
	at javax.mail.internet.MimeMessage.<clinit>(MimeMessage.java:182) ~[javax.mail-api-1.6.2.jar:1.6.2]
	at org.springframework.mail.javamail.JavaMailSenderImpl.createMimeMessage(JavaMailSenderImpl.java:341) ~[spring-context-support-5.3.14.jar:5.3.14]
	at com.example.demo.mail.EmailService.sendMail(EmailService.java:19) ~[main/:na]
	at com.example.demo.mail.EmailController.send(EmailController.java:15) ~[main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_312]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.14.jar:5.3.14]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.14.jar:5.3.14]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.14.jar:5.3.14]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.14.jar:5.3.14]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.14.jar:5.3.14]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.14.jar:5.3.14]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067) ~[spring-webmvc-5.3.14.jar:5.3.14]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.14.jar:5.3.14]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.14.jar:5.3.14]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.14.jar:5.3.14]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-embed-core-9.0.56.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.14.jar:5.3.14]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.56.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.14.jar:5.3.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.14.jar:5.3.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.14.jar:5.3.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.14.jar:5.3.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.14.jar:5.3.14]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.14.jar:5.3.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.56.jar:9.0.56]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_312]
```
`ClassNotFoundException` 계속 발생..
내생각엔 bean이 제대로 등록되지 않아서 그런거같은데..ㅠ
```java
@Configuration
public class MailAuthConfiguration {
    @Bean({"mailSender"})
    public JavaMailSender getJavaMailSender() {
        Properties properties = new Properties();
        properties.put("mail.smtp.auth", true);
        properties.put("mail.transport.protocol", "smtp");
        properties.put("mail.smtp.starttls.enable", true);
        properties.put("mail.smtp.starttls.required", true);
        properties.put("mail.debug", true);

        JavaMailSenderImpl mailSender = new JavaMailSenderImpl();
        mailSender.setHost("smtp.gmail.com");
        mailSender.setPort(587);
        mailSender.setUsername("kyu@mecross.co.kr");
        mailSender.setPassword("qweqwe11");
        mailSender.setDefaultEncoding("utf-8");
        mailSender.setJavaMailProperties(properties);

        return mailSender;

    }
```
bean이 제대로 등록되어있는지 확인해보자
https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=kbh3983&logNo=220876632483

**Comment by kyupid** [comment]
근데 IDE에서는 등록되어있다고 나옴 어쨋든
![image](https://user-images.githubusercontent.com/59721293/147717978-ed5957cb-2cb4-47ea-9314-984e7f900a38.png)

**Comment by kyupid** [comment]
테스트해보니 bean 등록되어있음
```java
@SpringBootTest(classes = DemoApplication.class)
class DemoApplicationTests {

	@Autowired
	private ApplicationContext applicationContext;

	@Test
	public void contextLoads() throws Exception {
		if (applicationContext != null) {
			String[] beans = applicationContext.getBeanDefinitionNames();

			for (String bean : beans) {
				System.out.println("bean : " + bean);
			}
		}
	}
}
```
코드: https://kim-jong-hyun.tistory.com/21
![image](https://user-images.githubusercontent.com/59721293/147718315-2fea47a1-f1a4-4199-9a2d-5f6db081eb9a.png)

**Comment by kyupid** [comment]
아 찾았다
[java.lang.ClassNotFoundException: com.sun.mail.util.MailLogger [java mail 스프링에서 메일 보내기 이게 딱 정답이에요 딴거보면 헷깔림]](https://9aram.tistory.com/28)

---

ㅇㅋㅇㅋ 해결

**Comment by kyupid** [comment]
### 회원가입 인증키 어떤 형식으로 저장?
```
개인적으로 프로젝트 경험으로 이메일 인증을 구현했을 시 저는

회원가입->이메일주소와 datetime을 베이스로한 sha256 hash 생성 ->

생성된 해시를 데이터베이스에 생성, 이메일 전송

가입자가 이메일에서 해시코드를 파라미터로 가지는 인증 url을 클릭했을 시 DB에서 해당 해시값은 인증되었고, users 테이블에서 인증 플래그를 올려줬었습니다.

해시값을 사용했기 때문에 딱히 암/복호화를 하지는 않았던 것 같습니다. 
```
https://okky.kr/article/331681

**Comment by kyupid** [comment]
### SMTP 오류 코드 정리
https://m.blog.naver.com/james2021/30170373091
▶ SERVER REPLY: 501 Denied domain name
: 도메인주소를 잘못 입력 or 수신측에서 도메인을 수신거부한 경우


▶ 421 Server too busy.

: 수신측 서버의 응답지연. 수신서버의 트래픽등으로 메일을 수신 받지 못하는 상황임


▶ 421-Microsoft ESMTP MAIL Service, Version: 5.0.2195.5600 ready at Service not
available, closing transmission channel

: MS사의 smtp 서버의 장애로 인해 메일을 수신받지 못하는 상황


▶ 421 4.3.2 Your IP(xxx.xxx.xxx.xxx) is filtered and this connection will be closed.

You must register your IP to yy@bbb.com By SpaceLee, the Lord of mail

server.

: 외부에서 @bbb.com 으로로 메일을 발송시 CHOL수신서버의 필터링 조건에 위배되어

스패머로 인식되고 필터링 되어 발신자에게 리턴되는 메시지.


▶ 421 4.4.0 IP ADDRESS: Closing connection by timeout

: 시간초과로 메일 수신 서버 접속이 끊겼습니다. 다시 접속해 주시기 바랍니다.


▶ 421 4.7.0 IP ADDRESS: Too many bad commands

: 사용 불가능한 명령어의 제한 수를 초과하였습니다. 명령어를 확인 후 다시 입력하시기 바랍니다.


▶ 421 4.7.0 IP ADDRESS: Too many transactions

:한 번 접속 후 접속을 끊지 않고 계속해서 메일을 발송할 경우,

일정양의 메일 수신후 한메일 서버에서 더 이상의 메일수신을 거부함.

메일 발송 시, 기존 접속을 끊고 새로운 접속을 맺으셔야 함


▶ 441 4.4.1 No answer from host

: 수신측 서버의 응답이 없슴.


▶ 450 4.5.3 IP ADDRESS: Too many recipients

: 수신서버가 한번에 받을수 있는 받는이 수 제한을 초과

받는이를 나눠서 메일을 재발송 요망


▶ 450 4.7.1 IP ADDRESS: Message refused. Your IP address has sent too many mails(MAIL COUNT).

: 수신메일에서 전송 가능한 메일 통수를 초과함.


▶ 451 4.2.0 IP ADDRESS: Temporary home error: RECIPIENT ADDRESS

: 받는이의 한메일 홈서버에 일시적인 장애가 있어서 메일을 수신할 수가 없음.

잠시 후 다시 시도 요망


▶ 451 4.4.1 IP ADDRESS: Network is busy(TYPE)

: 보낸이의 메일주소가 유효한 사용자인지 확인하던 중, 일시적인 오류가 발생.

잠시 후 재전송을 시도 요망


▶ 451 4.4.0 DNS resolving error

: 수신측 서버의 도메인을 못찾아 리턴됨.


▶ 451 4.3.0 Other or undefined mail system status

: 수신측 메일 시스템의 프로토콜이 틀리거나 수신 smtp 서버가 아닐경우


▶ 451 4.3.0 Temporary system failure. Please try again later.

: 수신 서버의 일시적인 장애로 인해 메일을 전송하지 못한 경우.


▶ 451 4.4.2 Bad connection (io timeout)

: 수신 서버의 응답이 없어서 응답시간이 초과 되어 리턴됨


▶ 451 Relay Server Not Ready.

: 수신측 서버에서 릴레이 기능이 안돼어 리턴된 메시지.


▶ 452 4.4.5 Insufficient disk space; try again later

: 수신서버의 디스크용량이 부족하여 메일을 수신받지 못한 경우.


▶ 452 4.4.5 ... Insufficient disk space; try again later

: 수신자(userid@xxx.xxx)의 메일함 용량이 부족하여 메일을 수신받지 못함


▶ 500 Syntax Error, Command Unrecognized EHLO mailsnd1.chollian.net


▶ 500 5.5.0 IP ADDRESS: Command line too long

: 명령어가 제한길이인 8,192 바이트를 초과.
명령어를 확인 후 다시 입력해야 함


▶ 500 5.5.1 Command unrecognized: "XXXX mailsnd1.chollian.net"


▶ 500 5.5.2 IP ADDRESS: Command not recognized: UNRECOGNIZED COMMAND

: 수신 서버가 이해할 수 없는 명령어임.

SMTP 규약에 맞게 수정 후 다시 입력해야 함


▶ 502 Not implemented

: 발송자의 메일 발송기(아웃룩, 유도라 등등)에서 메일발송시 수신측 메일 서버에서

SMTP 명령어를 인식하지 못함


▶ 501 5.1.8 Sender domain must exist(abc.xxx)

: 수신측 도메인(abc.xxx) 이 존재 하지 않음


▶ 501 5.5.2 IP ADDRESS: Syntax error in command line: COMMAND LINE

: 명령어 구문에 오류가 있음

SMTP 규약에 맞게 수정 후 다시 입력해야함


▶ 501 5.5.4 IP ADDRESS: EHLO requires domain name

: EHLO 명령어에 도메인 명이 포함되어 있지 않아 반송되었음

도메인 명을 포함한 명령어를 다시 입력해야함


▶ 501 5.5.4 IP ADDRESS: Command argument required

: 명령어에 필요한 인자값이 없음.

SMTP 규약에 맞게 수정 후 다시 입력해야함


▶ 501 5.5.4 IP ADDRESS: Invalid command argument: ARGUMENT

: 명령어 중 인자의 포맷이 올바르지 않음.

SMTP 규약에 수정 다시 입력해야함


▶ 503 5.5.1 IP ADDRESS: MAIL command required

: 받는이의 메일주소를 정의하기 전에 반드시 보낸이의 메일주소를 정의하여야 함.

SMTP 규약에 맞게 명령어를 다시 입력 요망


▶ 503 5.5.1 IP ADDRESS: Sender already specified

: 보낸이의 메일 주소가 이미 정의되어 있음.

SMTP 규약에 따라 보낸이의 메일주소는 중복해서 정의될 수 없음.

명령어를 확인하신 후 다시 발송시도 요망.


▶ 503 5.5.1 IP ADDRESS: RCPT command required(recipient)

: 받는이의 메일주소가 정의되지 않았음.

1명 이상의 받는이 주소를 포함시켜 다시 발송 요망


▶ 505 Authentication required

: 수신측 서버가 릴레이 인증 등을 허용하지 않음


▶ 512 5.1.2 Bad destination system address

: 수신 서버의 장애나 네트웍 트래픽등으로 인해 수신서버가 응답이 없는 경우


▶ 550 Mail is reject ( filtering reject )

: 수신 서버에서 발신자의 메일 주소나 IP를 필터링 하여 거부된 경우


▶ 550 Requested action not taken: mailbox unavailable

: 수신자의 메일함을 찾지 못해 리턴된 메시지.


▶ 550 Invalid recipient userid@xxx.xxx

: 수신자 계정을 찾지 못해 리턴된 경우


▶ 550 RCPT ERROR. Mailbox doesn't exist

: 수신자 메일함이 존재 하지 않음


▶ 550 5.1.1 Suspended user

: 수신e-mail주소 사용자의 계정이 중단된 상태.


▶ 550 5.1.1 IP ADDRESS: No such user: RECIPIENT ADDRESS

: 받는이의 메일주소가 가입되지 않은 아이디

받는이 주소를 확인 후 다시 발송해 요망


▶ 550 5.1.2 ... Unsupported mail destination

: 수신 서버가 응답이 지연


▶ 550 5.1.8 IP ADDRESS: No such user: SENDER ADDRESS

: 보낸이의 메일 주소가 가입되지 않은 아이디.

보낸이 주소를 확인 후, 재 발송 요망


▶ 550 5.7.1 ... Access denied.(123.456.78.11)

: 수신자(userid@xxx.xxx)가 발신자의 메일주소를 수신 거부한 상태.


▶ 550 5.7.1 ... Relaying denied. IP name lookup failed

: 수신 서버에서 발신자의 IP에 대해 릴레이 거부를 하여 메일을 보내지 못하는 경우.


▶ 550 5.1.1 ... User unknown

: 수신자 (userid@xxx.xxx)계정을 찾지 못한 경우.


▶ 550 5.2.0 IP ADDRESS: Message refused by the recipient: RECIPIENT ADDRESS

: 받는이가 보낸이 주소를 ‘수신거부’ 혹은 ‘바로삭제’로 설정하여 메일이 전달될 수 없음.


▶ 550 5.2.1 IP ADDRESS: Mailbox is inactive: RECIPIENT ADDRESS

: 받는이가 로그인한지 3개월 이상 지나 휴면계정으로 전환된 사용자

휴면 사용자는 메일을 수신할 수 없습니다.


▶ 550 5.7.1 Unable to relay for aa@aaa.com

: 수신 서버에서 릴레이 거부를 한 경우

▶ 550 5.1.8 IP ADDRESS: No such user: SENDER ADDRESS

: 보낸이의 메일 주소가 가입되지 않은 아이디

보낸이 주소를 확인 후, 재 발송 요망.


▶ 552 5.2.2 IP ADDRESS: Mailbox is full: RECIPIENT ADDRESS

: 받는이의 편지함이 가득 차서 더 이상 메일을 수신할 수 없음

받는이에게 다른 방법으로 연락이 가능하시다면 한메일의 편지함 정리를 요청해야 함


▶ 552 5.2.3 IP ADDRESS: Message size exceeds the limit(LIMIT)

: 메일이 수신 제한 용량을 초과

사이즈를 줄여 다시 발송 요망


▶ 553 sorry, your envelope sender is enlisted as spammer.

: 발신자의 메일 주소가 수신서버상의 스패머 리스트에 등록된 경우.


▶ 553-This target address is not our MX service

: 수신자의 주소가 수신서버에서 서비스 안하는 도메인일 경우


▶ 553 sorry, your envelope sender is in my badmailfrom list

: 발신자의 메일 주소가 수신서버상에서 블랙리스트에 올라 거부되어 리턴됨.


▶ 553 sorry, that domain isn't in my list of allowed rcpt hosts

: 발신자의 메일 도메인주소 자체가 수신 서버에서 차단된 경우.


▶ 553 5.1.2 IP ADDRESS: Relaying denied: RECIPIENT ADDRESS

: 정상적인 주소(@xxx.xom) 아닌 주소로 메일을 발송함

받는이 메일 주소를 확인 후, 다시 발송 요망


▶ 553 5.1.3 IP ADDRESS: Invalid mail address: RECIPIENT ADDRESS

: 받는이의 메일 주소가 정확하지 않음.

확인후 재발송 요청


▶ 553 5.1.7 IP ADDRESS: Invalid mail address: SENDER ADDRESS

: 보낸이의 메일 주소가 수신 서버에서 확인되지 않는 주소

보낸이 주소를 확인 후, 재발송 요망


▶ 553 5.1.8 ... Domain of sender address userid@xxx.xxx does not exist

: 발신자의 도메인에 대해 수신서버에서 체크 하여 없는 도메인일 경우.


▶ 553 5.0.0 We do not accept mail from spammers - If you have questions,please email admin@www.xxx.xxx.

: 발신자의 메일 계정이 스패머로 수신서버에서 등록이 되어 리턴됨.


▶ 553 5.0.0 Your message may contain the Win32.Klez worm!!- If you have questions,please email postmaster@xxx.xxx.

: 발신자의 메일에서 Win32.Klez 라는 웜바이러스가 발견되어 리턴.


▶ 553 5.3.0 ... spam

: 발송자의 계정이 수신서버 상에서 스패머로 등록이 되어 메일 수신 거부한 경우


▶ 554 1048035239.13309.hanmir accept failed. [code=-1]

: hanmir 서버에서 응답이 없슴.


▶ 554 delivery error: dd Sorry, your message to userid@yahoo.co.kr cannot be delivered. This account is over quota. - mta111.mail.yahoo.co.kr

: 수신자의 메일함 용량 초과로 인해 리턴됨


▶ 554 : Recipient address rejected: Access denied

: 수신자가 발신자의 계정에 대해 수신 거부를 설정함.


▶ 554 5.1.0 Sender Denied

: 발신자의 계정을 수신서버에서 수신 거부함.


▶ 554 5.3.2 Rejected by mailbox host. REPLY:(250 ... Sender ok)

: 수신자가 발송자의 메일 계정에 대해 수신 거부를 하여 리턴된 메시지 .


▶ 554 5.3.0 Mail have traversed Too many hops. Reject it.

: 발신자가 메일을 보낼 때 동보메일로 수신주소를 수신서버의 제한량 이상으로 보낸 경우


▶ 554 5.3.2 Rejected by mailbox host. REPLY:(550 5.1.1 unknown or illegal alias: userid@xxx.xxx)

: 수신자가 발송자의 메일 계정에 대해 수신거부를 설정하여 리턴됨.

 

▶ 554 5.4.6 IP ADDRESS: Routing loop detected

: 한메일 수신 서버가 이미 해당 메일을 수신했음

발송 서버의 루핑이 예상되오니, 확인해야 함.


▶ 554 5.6.0 IP ADDRESS: Message requires 'From' header

: 헤더에 보낸이 정보가 없는 경우 수신을 거부.

정확한 보낸이 주소를 포함하여 다시 발송요망


▶ 554 5.6.0 IP ADDRESS: Invalid 'From' header: FROM

: 헤더의 보낸이 정보가 ‘RFC2822 인터넷 메시지 규정’에 맞지 않는 경우 수신을 거부

RFC 규정을 참고 후, 다시 발송 요망


▶ 554 5.7.1 IP ADDRESS: Message refused. Your host name(HOST NAME) dosen't match with your IP address.

: 메일발송 IP 정보와 Hostname 정보가 일치하지 않아 해당 메일 수신을 거부

발송 서버에 ‘MX레코드’와 ‘리버스 도메인’이 등록되어 있는지 확인요청.

2개 모두 정확히 등록되어 있어야 함.

도메인 설정이 정확한지 네트워크 담당자에게 문의요망


▶ 554 5.7.1 IP ADDRESS: Message refused. Your domain(DOMAIN) has sent too many mails.

: 해당 도메인에서 너무 많은 메일이 발송되어, 메일 수신이 원활하지 않음

잠시 후 다시 발송 요청


▶ 554 5.7.7 IP ADDRESS: Message not terminated by end with "." on a line by itself

: DATA 명령어가 끝나기 전에 클라이언트가 닫혔기 때문에 해당 메일을 전달할수 없음

SMTP 규약에 따라 “.” 명령어를 포함하여 다시 입력 요망


▶ 554 5.7.1 IP ADDRESS: Connection refused. Your IP address is blocked.

: 메일서버에서 해당IP를 스팸IP로 판단하여 접속을 차단.

 

Thanks to 출처: http://moonset.tistory.com/133

**Comment by ghojeong** [comment]
우와 이건 뭐죠.
이건 저도 모르는 건데, Kyu 에게 배우러 가야겠네요.
대단합니다. Kyu
다음에 로그인 어떻게 하는지 알려주세요.

**Comment by kyupid** [comment]
메일로 링크오면 그거 클릭하면 회원가입되는 기능 있잖아요 그거하고 구현있어요 ㅋㅋㅋㅋ...대단하긴요...................ㅠ

**Comment by ghojeong** [comment]
나중에 Kyu CTO 되시면 저 불러주세요.
Kyu 랑도 언제 한번 같이 일해보고 싶네요.
